from django.urls import path
from .views import *

urlpatterns = [
    path('', KeyPageView.as_view()),
    path('signup/', SignupView.as_view()),
    path('get_code_for_confirm_registration/', GetCodeForConfirmRegistrationView.as_view()),
    path('confirm_registration/', ConfirmRegistrationView.as_view()),
    path('usual_login/', UsualLoginView.as_view()),
    path('login_with_code/', LoginWithCodeView.as_view()),
    path('logout/', LogoutView.as_view()),
    path('advertisements/', AdvertisementsListView.as_view()),
    path('advertisements/<int:pk>/', AdvertisementDetailView.as_view()),
    path('advertisements/create/', AdvertisementsCreateView.as_view()),
    path('advertisements/replies/', RepliesOnAdsView.as_view()),
    path('advertisements/<int:pk>/replies/', RepliesOnAdView.as_view()),
    path('advertisements/<int:pk>/replies/<int:pk>/', ReplyOnAdView.as_view()),
    path('advertisements/<int:pk>/replies/create/', RepliesCreateView.as_view()),
    path('advertisements/your_replies/', YourRepliesOnAdsView.as_view()),
    path('advertisements/<int:pk>/your_replies/', YourRepliesOnAdView.as_view()),
    path('advertisements/<int:pk>/your_replies/<int:pk>/', YourReplyOnAdView.as_view()),
    path('advertisements/<int:pk>/your_replies/<int:pk>/update/', YourRepliesUpdateView.as_view()),
    path('advertisements/<int:pk>/your_replies/<int:pk>/delete/', YourRepliesDeleteView.as_view()),
    path('your_advertisements/', YourAdvertisementsListView.as_view()),
    path('your_advertisements/<int:pk>/', YourAdvertisementDetailView.as_view()),
    path('your_advertisements/<int:pk>/update/', YourAdvertisementsUpdateView.as_view()),
    path('your_advertisements/<int:pk>/delete/', YourAdvertisementsDeleteView.as_view()),
    path('your_advertisements/replies/', RepliesOnYourAdsView.as_view()),
    path('your_advertisements/<int:pk>/replies/', RepliesOnYourAdView.as_view()),
    path('your_advertisements/<int:pk>/replies/<int:pk>/', ReplyOnYourAdView.as_view()),
    path('your_advertisements/<int:pk>/replies/<int:pk>/accept/', RepliesAcceptView.as_view()),
    path('signup_error/', SignupErrorView.as_view()),
    path('get_code_for_confirm_registration_error/', GetCodeForConfirmRegistrationErrorView.as_view()),
    path('confirm_registration_error/', ConfirmRegistrationErrorView.as_view()),
    path('usual_login_error/', UsualLoginErrorView.as_view()),
    path('login_with_code_error/', LoginWithCodeErrorView.as_view()),
]
