from django.urls import path
from .views import *

urlpatterns = [
    path('', KeyPageView.as_view()),
    path('signup/', SignupView.as_view()),
    path('get_code_for_confirm_registration/', GetCodeForConfirmRegistrationView.as_view()),
    path('confirm_registration/', ConfirmRegistrationView.as_view()),
    path('usual_login/', UsualLoginView.as_view()),
    path('login_with_code/', LoginWithCodeView.as_view()),
    path('logout/', LogoutView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('user_update/', UserUpdateView.as_view()),
    path('user_delete/', UserDeleteView.as_view()),
    path('advertisements/', AdvertisementsListView.as_view()),
    path('advertisements/<int:pk1>/', AdvertisementDetailView.as_view()),
    path('advertisements/create/', AdvertisementsCreateView.as_view()),
    path('advertisements/replies/', RepliesOnAdsView.as_view()),
    path('advertisements/<int:pk1>/replies/', RepliesOnAdView.as_view()),
    path('advertisements/<int:pk1>/replies/<int:pk2>/', ReplyOnAdView.as_view()),
    path('advertisements/<int:pk1>/replies/create/', RepliesCreateView.as_view()),
    path('advertisements/your_replies/', YourRepliesOnAdsView.as_view()),
    path('advertisements/<int:pk1>/your_replies/', YourRepliesOnAdView.as_view()),
    path('advertisements/<int:pk1>/your_replies/<int:pk2>/', YourReplyOnAdView.as_view()),
    path('advertisements/<int:pk1>/your_replies/<int:pk2>/update/', YourRepliesUpdateView.as_view()),
    path('advertisements/<int:pk1>/your_replies/<int:pk2>/delete/', YourRepliesDeleteView.as_view()),
    path('your_advertisements/', YourAdvertisementsListView.as_view()),
    path('your_advertisements/<int:pk1>/', YourAdvertisementDetailView.as_view()),
    path('your_advertisements/<int:pk1>/update/', YourAdvertisementsUpdateView.as_view()),
    path('your_advertisements/<int:pk1>/delete/', YourAdvertisementsDeleteView.as_view()),
    path('your_advertisements/replies/', RepliesOnYourAdsView.as_view()),
    path('your_advertisements/<int:pk1>/replies/', RepliesOnYourAdView.as_view()),
    path('your_advertisements/<int:pk1>/replies/<int:pk2>/', ReplyOnYourAdView.as_view()),
    path('your_advertisements/<int:pk1>/replies/<int:pk2>/accept/', RepliesAcceptView.as_view()),
    path('your_advertisements/<int:pk1>/replies/<int:pk2>/delete/', RepliesDeleteView.as_view()),
    path('signup_error/', SignupErrorView.as_view()),
    path('get_code_for_confirm_registration_error/', GetCodeForConfirmRegistrationErrorView.as_view()),
    path('confirm_registration_error/', ConfirmRegistrationErrorView.as_view()),
    path('usual_login_error/', UsualLoginErrorView.as_view()),
    path('login_with_code_error/', LoginWithCodeErrorView.as_view()),
    path('user_update_error/', SignupErrorView.as_view()),
    path('user_delete_error/', SignupErrorView.as_view()),
]
