# Generated by Django 5.2.5 on 2025-08-28 16:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_app', '0002_onetimecode_create_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
