# Generated by Django 5.2.5 on 2025-08-28 16:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_app', '0003_alter_advertisement_content_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
