# Generated by Django 5.2.5 on 2025-08-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_app', '0004_alter_advertisement_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='is_accepted',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Не принят', 'Не принят')], default='Не принят', max_length=9),
        ),
    ]
