# Generated by Django 5.2.5 on 2025-08-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_app', '0005_alter_reply_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
